# GoReleaser config for pgwd
# https://goreleaser.com
# Release: merge develop → main, git tag v0.1.0, then make release
# Snapshot (no tag): make snapshot

version: 2

builds:
  - id: pgwd
    main: ./cmd/pgwd
    binary: pgwd
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.Version=v{{ .Version }}
      - -X main.Commit={{ .ShortCommit }}
      - -X main.BuildDate={{ .Date }}

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

nfpms:
  - id: default
    package_name: pgwd
    file_name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    description: Postgres Watch Dog - monitor PostgreSQL connections and notify via Slack/Loki
    vendor: "Hermes Rodríguez"
    homepage: https://github.com/hrodrig/pgwd
    license: MIT
    formats:
      - deb
      - rpm
    builds:
      - pgwd

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^test:"

release:
  github:
    owner: hrodrig
    name: pgwd

# Homebrew: publish cask to tap so users can "brew install hrodrig/pgwd/pgwd"
# Create repo https://github.com/hrodrig/homebrew-pgwd first. For CI, set HOMEBREW_TAP_TOKEN (PAT with repo scope).
homebrew_casks:
  - name: pgwd
    directory: Casks
    homepage: "https://github.com/hrodrig/pgwd"
    description: "Postgres Watch Dog - monitor PostgreSQL connections and notify via Slack/Loki"
    repository:
      owner: hrodrig
      name: homebrew-pgwd
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    url:
      verified: "github.com/hrodrig/pgwd/"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pgwd"]
          end
